version: '3.5'

services:

  angular-cli:
    container_name: angular-cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/angularapp'
      - '/home/angularapp/node_modules'
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true
